version: '3'

services:
    web:
      container_name: node_test
      restart: always
      build: .
      env_file: .env
      environment:
        - MONGO_USERNAME=$MONGO_USERNAME
        - MONGO_PASSWORD=$MONGO_PASSWORD
        - MONGO_HOSTNAME=mongo
        - MONGO_PORT=$MONGO_PORT
        - MONGO_DB=$MONGO_DB
      ports:
        - "3005:3005"
      links:
        - mongo
      depends_on:
        - mongo
      volumes:
        - .:/usr/src/app
    
    mongo:
      container_name: mongo_test
      image: mongo:6.0.3
      env_file: .env
      environment:
        - MONGO_INITDB_ROOT_USERNAME=$MONGO_USERNAME
        - MONGO_INITDB_ROOT_PASSWORD=$MONGO_PASSWORD
      ports:
        - "27017:27017"
      volumes:
        - mongodata:/data/db

volumes:
  mongodata:
  node_modules: 